import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="pt-4 mb-0 navbar navbar-expand-sm navbar-light bg-light">
          <div className="container">
            <div className="navbar-brand">
                <img className="img-fluid" src="/quips.png" href="/" style={{width: "18vh"}}/>
            </div>
            <button className="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav ms-auto mb-2 mb-lg-0" style={{whiteSpace: "nowrap"}}>
                <li className="nav-item">
                  <a className="nav-link" href="/">Home</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/technologies">Technologies</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/instruments">Instrument Booking</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/about">About Us</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/contact">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="bg-light mb-3">
          <div className="container bg-light">
            <hr className="m-0" />
            <div className="pt-1 pb-1 bg-light"><p><strong>Quantitative Imaging, Phenotyping and Sorting Platform</strong></p></div>
          </div>
        </div>
        {children}
        <footer  className="pt-3 mt-3 text-center text-lg-start bg-light text-muted" style={{bottom: 0, width: "100%"}}>
          <div className="container">
            <div className="row">
              <div className="col-sm-4">
                <p>QuIPS Platform<br/>Paul Albrechtsen Research Institute CCMB<br/>ON6015 - 675 McDermot Avenue<br/>Winnipeg, Manitoba<br/>R3E 0V9, Canada<br/><br/>Tele: 204-787-2844​</p>
              </div>
              <div className="col-sm-4"></div>
              <div className="col-sm-4 ms-auto">
                <img src="/paulA.png" className="img-fluid" style={{width: "57%"}}></img>
                <img src="/cancercare.png" className="img-fluid" style={{width: "43%"}}></img>
                <p className="mt-2">We acknowledge the generous donation from the Paul Albrechtson Foundation for the purchase of the platform, as well as the ongoing support from Manitobans through their kind donations through the CancerCare Manitoba Foundation.</p>
              </div>
            </div>
          </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"></script>
      </body>
    </html>
  )
}
